### ISSUE TITLE
in Atom new version 1.8.0， the package make file tab name disappear

### ISSUE THREAD

**Issue by SimplyY** [paulpflug/foldername-tabs#10]
we can see detail in pictures:

![](http://7xkpdt.com1.z0.glb.clouddn.com/7ef97ab5343ceb7bfa38fec9ceb756f2.png)

![](http://7xkpdt.com1.z0.glb.clouddn.com/a9ea99f697d51d387b637b0213400b42.png)

**Comment by paulpflug** [comment]
I can't reproduce on 1.8.0, do you use any other packages changing tabs?

**Comment by SimplyY** [comment]
none，，，maybe some other lead this bug

**Comment by paulpflug** [comment]
which os are you using?

**Comment by SimplyY** [comment]
infact osx and windows all has this question...

**Comment by SimplyY** [comment]
and before atom 1.8 , this question dosen t exsit, when i upgrade atom ,it appear

**Comment by paulpflug** [comment]
Ok, eventually it did show up for me, too. I fixed it in 0.2.0

thanks for reporting :+1:
