### ISSUE TITLE
Filenames completely hidden on narrow tabs

### ISSUE THREAD

**Issue by emileber** [paulpflug/foldername-tabs#12]
When enabled, this plugin only shows the icon and hides the filename on narrow tabs. 

![atom-foldername-tabs-on](https://cloud.githubusercontent.com/assets/3286135/19093123/da870754-8a57-11e6-9f34-33a23e8770c4.png)

What it should do:

![atom-foldername-tabs-off](https://cloud.githubusercontent.com/assets/3286135/19093133/e5e49a1c-8a57-11e6-9be0-0e6631125984.png)

All the options are at their default value.

My installed packages:

```
Community Packages (27) C:\Users\emile.bergeron.CAMINO\.atom\packages
├── atom-beautify@0.29.13
├── atom-jinja2@0.5.0
├── atom-terminal@0.8.0
├── autoclose-html@0.23.0
├── color-picker@2.2.2
├── docblockr@0.8.5
├── emmet@2.4.3
├── file-icons@1.7.19
├── foldername-tabs@0.2.1
├── git-plus@5.18.0
├── highlight-selected@0.11.2
├── language-salt@0.4.0
├── linter@1.11.16
├── linter-eslint@7.3.2
├── linter-jshint@3.0.0
├── linter-php@1.2.0
├── merge-conflicts@1.4.4
├── minimap@4.25.0
├── minimap-cursorline@0.2.0
├── minimap-find-and-replace@4.5.1
├── minimap-highlight-selected@4.4.0
├── open-recent@5.0.0
├── pigments@0.36.0
├── sass-compiler-autosave@0.5.0
├── split-diff@1.0.4
├── temporary-root@1.0.1
└── todo-show@1.7.0

└── (empty)
```

I'm on windows 10 64-bit pro.

**Comment by ChristopherFunk** [comment]
I am having a similar problem, I am using the Atom-Material-UI theme and when files are opened outside the project or when the tab is too small this happens: (In this case the names are larger than the tab)
![foldername-tabs1](https://cloud.githubusercontent.com/assets/8630493/19601704/074554c4-9770-11e6-95d0-35ccc1f7f3b0.png)

Looks like the CSS is getting messed up maybe? The Contents of the tab extend below the tab bar in my case here:
![foldername-tabs2](https://cloud.githubusercontent.com/assets/8630493/19601706/08fc44da-9770-11e6-9fe9-90296d0274e2.png)

Disabling this packages makes the file names behave as expected

**Comment by bradstewart** [comment]
I think this is related to `foldername-tabs` and the `file-icons` package. Adding this to my global stylesheet seems to have fixed it:

``` less
.file-icons-tab-pane-icon atom-pane .tab-bar {
  .tab .title[data-path]:before {
    position: relative;
    float: left;
    margin-right: 5px;
  }
}
```

**Comment by paulpflug** [comment]
cool fix, thanks :+1:

**Comment by Igor-Gold** [comment]
I'm having the same issue as @ChristopherFunk

**Comment by emileber** [comment]
I found that Atom natively shows the folder name on tabs of files with the same name making this plugin unnecessary for me now.

Maybe I'll try the fix if I feel like I would need the folder name on every tab.
