### ISSUE TITLE
Option to not limit folder name length

### ISSUE THREAD

**Issue by kankaristo** [paulpflug/foldername-tabs#3]
Thanks for a great package, this is fantastic when you have multiple files with the same name in different subdirectories!

The problem is, I also have subdirectories with the same name (like "meta" below).

I modified the code a little bit to not limit the directory name with ".../":
![screenshot from 2015-07-11 20 56 15](https://cloud.githubusercontent.com/assets/3522333/8634788/903adcbc-280f-11e5-9d19-e519ff954531.png)
![screenshot from 2015-07-11 20 56 29](https://cloud.githubusercontent.com/assets/3522333/8634789/94797374-280f-11e5-93ee-6fdd85c9f505.png)

Naturally, this will break when the package updates. Could this be added as a config option?

For really long directory paths, it could be useful to limit the string to maybe 15-20 characters, so that the above might become something like "../engine/meta", instead of just ".../meta".

**Comment by paulpflug** [comment]
Nice to hear you like the package :smile: 
I could add a config option. But I have to think it through first.

What are the most important folders? which one to cut out first?
The current solution (all but the last) clearly isn't the most intelligent ^^
I'm thinking about `last > first > second last > third last etc.` 
The coding wont be difficult but I'm unsure what is desirable behavior..

I could also shorten folder names with [abbreviate](https://github.com/paulpflug/abbreviate), which makes it even more complex

**Comment by kankaristo** [comment]
> I'm thinking about last > first > second last > third last etc.

I think that's probably the best default option. :+1:

---

There are 2 things to consider here: _how_ to limit and _when_ to limit. Both should probably be configurable, because making it "smart" enough to satisfy all users is impossible. Just think about all of the different themes, fonts, etc...

_How_ to limit the length could be a drop-down list (enum) with options like:
- last > first > 2nd last > 3rd last
- last > 2nd last > 3rd last

For knowing _when_ to limit, a maximum path length (in characters) would probably be the easiest way. So, if the user sets the maximum length to 20 (ignoring any `...` in between):
- always add last directory
- check if the first directory fits into 20 - `/` - last
- check if the 2nd last directory fits into 20 - `/` - last - `/` - first
- etc.

The "no limit" option could be active when the maximum length is set to 0.

**Comment by kankaristo** [comment]
`abbreviate` seems cool, that would definitely be better than just `...`, which offers no information and renders horribly at small font sizes...

Although, I am a bit worried because some tabs would be abbreviated differently than others, so sometimes "data" would be "dt", sometimes not... There's also a chance that it would abbreviate 2 different directory names in the same way, which would also be confusing.

**Comment by paulpflug** [comment]
have a look at 0.1.5 :smile:

**Comment by kankaristo** [comment]
Thanks, that's working well! :+1:

The "maximum path length" setting doesn't really seem to work though? If I set it to 0, it doesn't limit the path at all, but for non-zero values it doesn't seem to make a difference whether it's 5 or 500. I could have just misunderstood how it works. :P

I'm closing this issue, since not limiting at all is working well.

**Comment by paulpflug** [comment]
strange, it works for me..
You need the path to be at least 2 folders long, the last one will be displayed always

**Comment by kankaristo** [comment]
If I set it to 0, it doesn't shorten at all. But it doesn't seem to matter if it's set to 20 or 200, it only displays the last folder in the path (e.g. `path/to/folder` becomes `.../folder`).

The "maximum folder length" setting on the other hand seems to be working as intended.
