### ISSUE TITLE
Tabs reset to standard look once you drag & drop (reorder) a tab

### ISSUE THREAD

**Issue by bbhh** [paulpflug/foldername-tabs#4]
The tabs look great, but once I drag and drop a tab to reorder my tabs, the tab look and feel resets to the standard look and feel. So, if a tab had a two-line display with folder on top and file on bottom, once I drag it, it becomes a one-liner like "filename - folder", or "filename" if no folder is needed to be displayed.

Great package, thanks for creating this! It looks especially nice with the Seti theme.

**Comment by paulpflug** [comment]
Thanks for reporting :+1: 
I appreciate your praise :smile: 

I stumbled upon this already, but I think atom's API doesn't fire on reorder events.
The workspace is ordered in panes which, them self have paneItems and what I see there are only creating and destroying events
So currently there is no way of knowing when to redraw. you could create a Issue at the atom repository and request such events (they should exist really)

Once I can I will fix it..

**Comment by jerone** [comment]
Any update on this issue? The [pinned-tabs](https://github.com/ericcornelissen/pinned-tabs-for-atom) package seems to [activate the same issue](https://github.com/ericcornelissen/pinned-tabs-for-atom/issues/8) as described here.

**Comment by paulpflug** [comment]
finally found a way :smile:
should work in 0.1.7
(if it doesn't feel free to reopen)

**Comment by jerone** [comment]
Can't confirm this being fixed :disappointed: 
When reordering tabs the original state returns. 
No errors in the console.

However, when I close another tab, the reset-ed tab gets converted to foldername tab again. Almost there :smile: 

_Atom 1.5.0-beta1
Foldername Tabs 0.1.7
Material UI theme 0.8.1_

**Comment by jerone** [comment]
Looking at Atom's [tab code](https://github.com/atom/tabs/blob/master/lib/tab-bar-view.coffee#L233-L260) again I see no easy solution to hook into this.

One direction that might be interesting to try out is using a [`MutationObserver`](https://developer.mozilla.org/en/docs/Web/API/MutationObserver) on the tab-bar...

**Comment by paulpflug** [comment]
Ok now I understand. I only looked on drag and drop between panes, this works now. But within one pane it doesn't...

**Comment by paulpflug** [comment]
there is a hook [onDidMoveItem](https://atom.io/docs/api/v1.4.1/Pane#instance-onDidMoveItem)
should work in 0.1.8 :smile:

**Comment by jerone** [comment]
That's awesome. Testing it now...

_Edit:_
Confirmed working!

Ps. Would be great if you can update the changelog.
