### ISSUE TITLE
Sometimes shows wrong folder

### ISSUE THREAD

**Issue by rugk** [paulpflug/foldername-tabs#5]
![foldernamestabsdisplayissues](https://cloud.githubusercontent.com/assets/11966684/10552983/e1156ece-7457-11e5-95d7-1090997d0110.gif)

Here is how you can reproduce it (at last it worked in my case):
1. File -> New window in Atom
2. You can close the empty file.
3. Select two files.
4. Drag and drop them into Atom.

Atom 1.0.19
Windows 7

**Comment by paulpflug** [comment]
thanks for reporting. This doesn't occur on linux, very strange. On my windows a new instance of atom is opened on dropping, so I can't get in dev mode.

Additionally the two files are treated as folders in the tree view, so I belief it is a problem on atoms side.

**Comment by rugk** [comment]
If it's only happening on Windows it may have something to do with the directory characters (`/` on Linux and `\` on Windows). This is just an idea...

**Comment by paulpflug** [comment]
works for me on atom 1.4.0 in windows
